
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=embrapa
      - POSTGRES_USER=aleatorio
      - POSTGRES_PASSWORD=heyjoletsgo
    networks:
      - docker_compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "embrapa"]
      timeout: 5s
      retries: 10
  app:
    entrypoint: ./entrypoint.sh
    image: embrapa-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8009:80
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgresql://aleatorio:heyjoletsgo@host.docker.internal:5434/embrapa
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:

networks:
  docker_compose: