"""create tables

Revision ID: 827266b03d47
Revises: 
Create Date: 2024-05-21 02:54:13.389416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827266b03d47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercializacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('litros', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exportacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cultivar', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('litros', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_data',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('tokens',
    sa.Column('access_token', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('access_token')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users_in_db',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_in_db')
    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_table('token_data')
    op.drop_table('producao')
    op.drop_table('processamento')
    op.drop_table('importacao')
    op.drop_table('exportacao')
    op.drop_table('comercializacao')
    # ### end Alembic commands ###
